# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 18:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=100)),
                ('published', models.CharField(max_length=20)),
                ('isbn', models.CharField(max_length=15)),
                ('pages', models.CharField(max_length=5)),
                ('language', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='inserted')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='inserted')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_like_set', to='core.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_like_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='inserted')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_search_set', to='core.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('HR', 'Have Read'), ('AR', 'Am Reading'), ('WR', 'Want to Read')], default='AR', max_length=2)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='inserted')),
                ('edited', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_status_set', to='core.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_status_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
