# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-27 21:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170827_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='book',
        ),
        migrations.RemoveField(
            model_name='search',
            name='edited',
        ),
        migrations.AddField(
            model_name='search',
            name='term',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='search',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_search_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
